name: buzzby
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+11

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  crypto: ^3.0.3
  expandable_page_view: ^1.0.17
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  google_mobile_ads: ^3.1.0
  location: ^5.0.3
  modal_bottom_sheet: ^2.1.2
  onesignal_flutter: ^5.2.9
  smooth_page_indicator: ^1.1.0
  supabase_flutter: ^1.10.25

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
